server:
  port: 8081

logging:
  level:
    ROOT: info
    com.azercell.banking.common: DEBUG
    com.azercell.banking.identity: DEBUG

spring:
  application:
    name: ms-identity
  main:
    banner-mode: log
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
